### ISSUE TITLE
Illegal constructor 

### ISSUE THREAD

**Issue by arperyan** [crisward/svelte-tag#4]
Hi,

I keep getting this error: Illegal constructor. Maybe the reason is because I am using vite? The example is very basic with just hello world. Any ideas?

Many thanks,

Ryan Arpe

**Comment by crisward** [comment]
I'm also using this with vite... 🤔

**Comment by crisward** [comment]
My vite config looks like this, if it helps.

```javascript
import { defineConfig } from 'vite'
import svelte from '@sveltejs/vite-plugin-svelte'
import fs from "fs"

// https://vitejs.dev/config/
export default defineConfig(({ command, mode })=>{

return{
  plugins: [
    svelte({ hot: mode!="production"}),
  ],
  resolve:{
    browser: true,
    dedupe: ['svelte']
  },
  server:{
    port:8090,
  },
  publicDir:"storage/public/",
  build:{
    manifest: true,
    sourcemap: true,
    assetsDir:'site',
    rollupOptions:{
      input:{
        site:'/site/site.js',
      },
      output: {
        sourcemap: true,
        format: 'es',
        name: 'app',
        dir: 'storage/public/resources',
      }
    }
  }
}})

**Comment by arperyan** [comment]
Thanks, that was helpful. I think my last issue is, how do I import the component? I am doing this - import "../../public/resources";

**Comment by arperyan** [comment]
Hi,

I got a simple example working, but have tried to pass a object and an array to the web component. I noticed that its passing it as a string? eg "[object Object]"

Ryan Arpe

**Comment by crisward** [comment]
That's because the data is being passed as html attributes (which are always strings / booleans). 

To pass complex data you'll have to stringify it first, or target a property within your web component with javascript. Usually doing a `JSON.stringify` before you pass the data in, then getting your component to do a `JSON.parse` should work.

I typically only use svelte tag to wrap an app, and use normal svelte components internally as they have much better options when it comes to linking and updating data.

**Comment by arperyan** [comment]
Thanks for your quick response. I provide a team using Angular with visualisations, and I refuse to create them in Angular. So I need to pass data and a rendering engine into the svelte component. I will try your suggestion.
